<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProvincesController extends Controller
{
    public function provinsi()
    {
        return [
            [
                'name' => 'Aceh',
                'iso_code' => 'AC',
            ],
            [
                'name' => 'Bali',
                'iso_code' => 'BA',
            ],
            [
                'name' => 'Banten',
                'iso_code' => 'BT',
            ],
            [
                'name' => 'Bengkulu',
                'iso_code' => 'BE',
            ],
            [
                'name' => 'DKI Jakarta',
                'iso_code' => 'JK',
            ],
            [
                'name' => 'Gorontalo',
                'iso_code' => 'GO',
            ],
            [
                'name' => 'Jambi',
                'iso_code' => 'JA',
            ],
            [
                'name' => 'Jawa Barat',
                'iso_code' => 'JB',
            ],
            [
                'name' => 'Jawa Tengah',
                'iso_code' => 'JT',
            ],
            [
                'name' => 'Jawa Timur',
                'iso_code' => 'JI',
            ],
            [
                'name' => 'Kalimantan Barat',
                'iso_code' => 'KB',
            ],
            [
                'name' => 'Kalimantan Selatan',
                'iso_code' => 'KS',
            ],
            [
                'name' => 'Kalimantan Tengah',
                'iso_code' => 'KT',
            ],
            [
                'name' => 'Kalimantan Timur',
                'iso_code' => 'KI',
            ],
            [
                'name' => 'Kalimantan Utara',
                'iso_code' => 'KU',
            ],
            [
                'name' => 'Kepulauan Bangka Belitung',
                'iso_code' => 'BB',
            ],
            [
                'name' => 'Kepulauan Riau',
                'iso_code' => 'KR',
            ],
            [
                'name' => 'Lampung',
                'iso_code' => 'LA',
            ],
            [
                'name' => 'Maluku',
                'iso_code' => 'MA',
            ],
            [
                'name' => 'Maluku Utara',
                'iso_code' => 'MU',
            ],
            [
                'name' => 'Nusa Tenggara Barat',
                'iso_code' => 'NB',
            ],
            [
                'name' => 'Nusa Tenggara Timur',
                'iso_code' => 'NT',
            ],
            [
                'name' => 'Papua',
                'iso_code' => 'PA',
            ],
            [
                'name' => 'Papua Barat',
                'iso_code' => 'PB',
            ],
            [
                'name' => 'Riau',
                'iso_code' => 'RI',
            ],
            [
                'name' => 'Sulawesi Barat',
                'iso_code' => 'SR',
            ],
            [
                'name' => 'Sulawesi Selatan',
                'iso_code' => 'SN',
            ],
            [
                'name' => 'Sulawesi Tengah',
                'iso_code' => 'ST',
            ],
            [
                'name' => 'Sulawesi Tenggara',
                'iso_code' => 'SG',
            ],
            [
                'name' => 'Sulawesi Utara',
                'iso_code' => 'SA',
            ],
            [
                'name' => 'Sumatera Barat',
                'iso_code' => 'SB',
            ],
            [
                'name' => 'Sumatera Selatan',
                'iso_code' => 'SS',
            ],
            [
                'name' => 'Sumatera Utara',
                'iso_code' => 'SU',
            ],
            [
                'name' => 'Yogyakarta',
                'iso_code' => 'YO',
            ],
        ];
    }

    public function kota_kabupaten()
    {
        return [
            [
                'text' => 'Aceh',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Aceh Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Barat Daya'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Besar'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Jaya'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Singkil'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Tamiang'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Tenggara'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Aceh Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Bener Meriah'],
                    ['id' => 1, 'text' => 'Kabupaten Bireuen'],
                    ['id' => 1, 'text' => 'Kabupaten Gayo Lues'],
                    ['id' => 1, 'text' => 'Kabupaten Nagan Raya'],
                    ['id' => 1, 'text' => 'Kabupaten Pidie'],
                    ['id' => 1, 'text' => 'Kabupaten Pidie Jaya'],
                    ['id' => 1, 'text' => 'Kabupaten Simeulue'],
                    ['id' => 1, 'text' => 'Kota Banda Aceh'],
                    ['id' => 1, 'text' => 'Kota Langsa'],
                    ['id' => 1, 'text' => 'Kota Lhokseumawe'],
                    ['id' => 1, 'text' => 'Kota Sabang'],
                    ['id' => 1, 'text' => 'Kota Subulussalam'],
                ]
            ],
            [
                'text' => 'Bali',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Badung'],
                    ['id' => 1, 'text' => 'Kabupaten Bangil'],
                    ['id' => 1, 'text' => 'Kabupaten Buleleng'],
                    ['id' => 1, 'text' => 'Kabupaten Gianyar'],
                    ['id' => 1, 'text' => 'Kabupaten Jembrana'],
                    ['id' => 1, 'text' => 'Kabupaten Karangasem'],
                    ['id' => 1, 'text' => 'Kabupaten Klungkung'],
                    ['id' => 1, 'text' => 'Kabupaten Tabanan'],
                    ['id' => 1, 'text' => 'Kota Denpasar'],
                ]
            ],
            [
                'text' => 'Banten',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Lebak'],
                    ['id' => 1, 'text' => 'Kabupaten Pandeglang'],
                    ['id' => 1, 'text' => 'Kabupaten Serang'],
                    ['id' => 1, 'text' => 'Kabupaten Tangerang'],
                    ['id' => 1, 'text' => 'Kota Cilegon'],
                    ['id' => 1, 'text' => 'Kota Serang'],
                    ['id' => 1, 'text' => 'Kota Tangerang'],
                    ['id' => 1, 'text' => 'Kota Tangerang selatan'],
                ]
            ],
            [
                'text' => 'Bengkulu',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bengkulu Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Bemgkulu Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Bengkulu Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Kaur'],
                    ['id' => 1, 'text' => 'Kabupaten kapahiang'],
                    ['id' => 1, 'text' => 'Kabupaten Lebong'],
                    ['id' => 1, 'text' => 'Kabupaten Mukomuko'],
                    ['id' => 1, 'text' => 'Kabupaten Rejang Lebong'],
                    ['id' => 1, 'text' => 'Kabupaten seluma'],
                    ['id' => 1, 'text' => 'Kota Bengkulu'],
                ]
            ],
            [
                'text' => 'Yogyakarta',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bantul'],
                    ['id' => 1, 'text' => 'Kabupaten Gunung kildul'],
                    ['id' => 1, 'text' => 'Kabupaten Kulon Progo'],
                    ['id' => 1, 'text' => 'Kabupaten Sleman'],
                    ['id' => 1, 'text' => 'Kota Yogyakarta'],
                ]
            ],
            [
                'text' => 'DKI Jakarta',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Seribu'],
                    ['id' => 1, 'text' => 'Kota Jakarta Barat'],
                    ['id' => 1, 'text' => 'Kota Jakarta Pusat'],
                    ['id' => 1, 'text' => 'Kota Jakarta Selatan'],
                    ['id' => 1, 'text' => 'Kota Jakarta Timur'],
                    ['id' => 1, 'text' => 'Kota Jakarta Utara'],
                ]
            ],
            [
                'text' => 'Gorontalo',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Boalemo'],
                    ['id' => 1, 'text' => 'Kabupaten Bone Bolango'],
                    ['id' => 1, 'text' => 'Kabupaten Gorontalo'],
                    ['id' => 1, 'text' => 'Kabupaten gorontalo Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Pahuwato'],
                    ['id' => 1, 'text' => 'Kota Gorontalo'],
                ]
            ],
            [
                'text' => 'Jambi',
                'children' =>  [
                    ['id' => 1, 'text' => 'Kabupaten Batanghari'],
                    ['id' => 1, 'text' => 'Kabupaten Bungo'],
                    ['id' => 1, 'text' => 'Kabupaten Kerinci'],
                    ['id' => 1, 'text' => 'Kabupaten Merangin'],
                    ['id' => 1, 'text' => 'Kabupaten Muaro Jambi'],
                    ['id' => 1, 'text' => 'Kabupaten Sarolangun'],
                    ['id' => 1, 'text' => 'Kabupaten Tanjung Jabung Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Tanjung Jabung Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Tebo'],
                    ['id' => 1, 'text' => 'Kota Jambi'],
                    ['id' => 1, 'text' => 'Kota Sungai Penuh'],
                ]
            ],
            [
                'text' => 'Jawa Barat',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bandung'],
                    ['id' => 1, 'text' => 'Kabupaten Bandung Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Bekasi'],
                    ['id' => 1, 'text' => 'Kabupaten Bogor'],
                    ['id' => 1, 'text' => 'Kabupaten Ciamis'],
                    ['id' => 1, 'text' => 'Kabupaten Cianjur'],
                    ['id' => 1, 'text' => 'Kabupaten Cirebon'],
                    ['id' => 1, 'text' => 'Kabupaten Garut'],
                    ['id' => 1, 'text' => 'Kabupaten Indramayu'],
                    ['id' => 1, 'text' => 'Kabupaten Karawang'],
                    ['id' => 1, 'text' => 'Kabupaten Kuningan'],
                    ['id' => 1, 'text' => 'Kabupaten Majalengka'],
                    ['id' => 1, 'text' => 'Kabupaten Pangandaran'],
                    ['id' => 1, 'text' => 'Kabupaten Purwakarta'],
                    ['id' => 1, 'text' => 'Kabupaten Subang'],
                    ['id' => 1, 'text' => 'Kabupaten Sukabumi'],
                    ['id' => 1, 'text' => 'Kabupaten Sumedang'],
                    ['id' => 1, 'text' => 'Kabupaten Tasikmalaya'],
                    ['id' => 1, 'text' => 'Kota Bandung'],
                    ['id' => 1, 'text' => 'Kota Banjar'],
                    ['id' => 1, 'text' => 'Kota Bekasi'],
                    ['id' => 1, 'text' => 'Kota Bogor'],
                    ['id' => 1, 'text' => 'Kota Cimahi'],
                    ['id' => 1, 'text' => 'Kota Cirebon'],
                    ['id' => 1, 'text' => 'Kota Depok'],
                    ['id' => 1, 'text' => 'Kota Sukabumi'],
                    ['id' => 1, 'text' => 'Kota Tasikmalaya'],
                ]
            ],
            [
                'text' => 'Jawa Tengah',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Banjarnegara'],
                    ['id' => 1, 'text' => 'Kabupaten Banyumas'],
                    ['id' => 1, 'text' => 'Kabupaten Batang'],
                    ['id' => 1, 'text' => 'Kabupaten Blora'],
                    ['id' => 1, 'text' => 'Kabupaten Boyolali'],
                    ['id' => 1, 'text' => 'Kabupaten Brebes'],
                    ['id' => 1, 'text' => 'Kabupaten Cilacap'],
                    ['id' => 1, 'text' => 'Kabupaten Demak'],
                    ['id' => 1, 'text' => 'Kabupaten Grobogan'],
                    ['id' => 1, 'text' => 'Kabupaten Jepara'],
                    ['id' => 1, 'text' => 'Kabupaten Karanganyar'],
                    ['id' => 1, 'text' => 'Kabupaten Kebumen'],
                    ['id' => 1, 'text' => 'Kabupaten Kendal'],
                    ['id' => 1, 'text' => 'Kabupaten Klaten'],
                    ['id' => 1, 'text' => 'Kabupaten Kudus'],
                    ['id' => 1, 'text' => 'Kabupaten Magelang'],
                    ['id' => 1, 'text' => 'Kabupaten Pati'],
                    ['id' => 1, 'text' => 'Kabupaten Pekalongan'],
                    ['id' => 1, 'text' => 'Kabupaten Pemalang'],
                    ['id' => 1, 'text' => 'Kabupaten Purbalingga'],
                    ['id' => 1, 'text' => 'Kabupaten Purworejo'],
                    ['id' => 1, 'text' => 'Kabupaten Rembang'],
                    ['id' => 1, 'text' => 'Kabupaten Semarang'],
                    ['id' => 1, 'text' => 'Kabupaten Sragen'],
                    ['id' => 1, 'text' => 'Kabupaten Sukoharjo'],
                    ['id' => 1, 'text' => 'Kabupaten Tegal'],
                    ['id' => 1, 'text' => 'Kabupaten Temanggung'],
                    ['id' => 1, 'text' => 'Kabupaten Wonogiri'],
                    ['id' => 1, 'text' => 'Kabupaten Wonosobo'],
                    ['id' => 1, 'text' => 'Kota Magelang'],
                    ['id' => 1, 'text' => 'Kota Pekalongan'],
                    ['id' => 1, 'text' => 'Kota Salatiga'],
                    ['id' => 1, 'text' => 'Kota Semarang'],
                    ['id' => 1, 'text' => 'Kota Surakarta'],
                    ['id' => 1, 'text' => 'Kota Tegal'],
                ]
            ],
            [
                'text' => 'Jawa Timur',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bangkalan'],
                    ['id' => 1, 'text' => 'Kabupaten Banyuwangi'],
                    ['id' => 1, 'text' => 'Kabupaten Blitar'],
                    ['id' => 1, 'text' => 'Kabupaten Bojonegoro'],
                    ['id' => 1, 'text' => 'Kabupaten Bondowoso'],
                    ['id' => 1, 'text' => 'Kabupaten Gresik'],
                    ['id' => 1, 'text' => 'Kabupaten Jember'],
                    ['id' => 1, 'text' => 'Kabupaten Jombang'],
                    ['id' => 1, 'text' => 'Kabupaten Kediri'],
                    ['id' => 1, 'text' => 'Kabupaten Lamongan'],
                    ['id' => 1, 'text' => 'Kabupaten Lumajang'],
                    ['id' => 1, 'text' => 'Kabupaten Madiun'],
                    ['id' => 1, 'text' => 'Kabupaten Magetan'],
                    ['id' => 1, 'text' => 'Kabupaten Malang'],
                    ['id' => 1, 'text' => 'Kabupaten Mojokerto'],
                    ['id' => 1, 'text' => 'Kabupaten Nganjuk'],
                    ['id' => 1, 'text' => 'Kabupaten Ngawi'],
                    ['id' => 1, 'text' => 'Kabupaten Pacitan'],
                    ['id' => 1, 'text' => 'Kabupaten Pamekasan'],
                    ['id' => 1, 'text' => 'Kabupaten Pasuruan'],
                    ['id' => 1, 'text' => 'Kabupaten Ponorogo'],
                    ['id' => 1, 'text' => 'Kabupaten Probolinggo'],
                    ['id' => 1, 'text' => 'Kabupaten Sampang'],
                    ['id' => 1, 'text' => 'Kabupaten Sidoarjo'],
                    ['id' => 1, 'text' => 'Kabupaten Situbondo'],
                    ['id' => 1, 'text' => 'Kabupaten Sumenep'],
                    ['id' => 1, 'text' => 'Kabupaten Trenggalek'],
                    ['id' => 1, 'text' => 'Kabupaten Tuban'],
                    ['id' => 1, 'text' => 'Kabupaten Tulungagung'],
                    ['id' => 1, 'text' => 'Kota Batu'],
                    ['id' => 1, 'text' => 'Kota Blitar'],
                    ['id' => 1, 'text' => 'Kota Kediri'],
                    ['id' => 1, 'text' => 'Kota Madiun'],
                    ['id' => 1, 'text' => 'Kota Malang'],
                    ['id' => 1, 'text' => 'Kota Mojokerto'],
                    ['id' => 1, 'text' => 'Kota Pasuruan'],
                    ['id' => 1, 'text' => 'Kota Probolinggo'],
                    ['id' => 1, 'text' => 'Kota Surabaya'],
                ]
            ],
            [
                'text' => 'Kalimantan Barat',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bengkayang'],
                    ['id' => 1, 'text' => 'Kabupaten Kapuas Hulu'],
                    ['id' => 1, 'text' => 'Kabupaten Kayong Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Ketapang'],
                    ['id' => 1, 'text' => 'Kabupaten Kubu Raya'],
                    ['id' => 1, 'text' => 'Kabupaten Landak'],
                    ['id' => 1, 'text' => 'Kabupaten Melawi'],
                    ['id' => 1, 'text' => 'Kabupaten Pontianak'],
                    ['id' => 1, 'text' => 'Kabupaten Sambas'],
                    ['id' => 1, 'text' => 'Kabupaten Sanggau'],
                    ['id' => 1, 'text' => 'Kabupaten Sekadau'],
                    ['id' => 1, 'text' => 'Kabupaten Sintang'],
                    ['id' => 1, 'text' => 'Kota Pontianak'],
                    ['id' => 1, 'text' => 'Kota Singkawang'],
                ]
            ],
            [
                'text' => 'Kalimantan Selatan',
                'children' =>  [
                    ['id' => 1, 'text' => 'Kabupaten Balangan'],
                    ['id' => 1, 'text' => 'Kabupaten Banjar'],
                    ['id' => 1, 'text' => 'Kabupaten Barito Kuala'],
                    ['id' => 1, 'text' => 'Kabupaten Hulu Sungai Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Hulu Sungai Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Hulu Sungai Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Kotabaru'],
                    ['id' => 1, 'text' => 'Kabupaten Tabalong'],
                    ['id' => 1, 'text' => 'Kabupaten Tanah Bumbu'],
                    ['id' => 1, 'text' => 'Kabupaten Tanah Laut'],
                    ['id' => 1, 'text' => 'Kabupaten Tapin'],
                    ['id' => 1, 'text' => 'Kota Banjarbaru'],
                    ['id' => 1, 'text' => 'Kota Banjarmasin'],
                ]
            ],
            [
                'text' => 'Kalimantan Tengah',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Barito Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Barito Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Barito Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Gunung Mas'],
                    ['id' => 1, 'text' => 'Kabupaten Kapuas'],
                    ['id' => 1, 'text' => 'Kabupaten Katingan'],
                    ['id' => 1, 'text' => 'Kabupaten Kotawaringin Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Kotawaringin Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Lamandau'],
                    ['id' => 1, 'text' => 'Kabupaten Murung Raya'],
                    ['id' => 1, 'text' => 'Kabupaten Pulang Pisau'],
                    ['id' => 1, 'text' => 'Kabupaten Sukamara'],
                    ['id' => 1, 'text' => 'Kabupaten Seruyan'],
                    ['id' => 1, 'text' => 'Kota Palangka Raya'],
                ]
            ],
            [
                'text' => 'Kalimantan Timur',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Berau'],
                    ['id' => 1, 'text' => 'Kabupaten Kutai Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Kutai Kartanegara'],
                    ['id' => 1, 'text' => 'Kabupaten Kutai Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Paser'],
                    ['id' => 1, 'text' => 'Kabupaten Penajam Paser Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Mahakam Ulu'],
                    ['id' => 1, 'text' => 'Kota Balikpapan'],
                    ['id' => 1, 'text' => 'Kota Bontang'],
                    ['id' => 1, 'text' => 'Kota Samarinda'],
                ]
            ],
            [
                'text' => 'Kalimantan Utara',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bulungan'],
                    ['id' => 1, 'text' => 'Kabupaten Malinau'],
                    ['id' => 1, 'text' => 'Kabupaten Nunukan'],
                    ['id' => 1, 'text' => 'Kabupaten Tana Tidung'],
                    ['id' => 1, 'text' => 'Kota Tarakan'],
                ]
            ],
            [
                'text' => 'Kepulauan Bangka Belitung',
                'children' =>  [
                    ['id' => 1, 'text' => 'Kabupaten Bangka'],
                    ['id' => 1, 'text' => 'Kabupaten Bangka Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Bangka Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Bangka Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Belitung'],
                    ['id' => 1, 'text' => 'Kabupaten Belitung Timur'],
                    ['id' => 1, 'text' => 'Kota Pangkal Pinang'],
                ]
            ],
            [
                'text' => 'Kepulauan Riau',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bintan'],
                    ['id' => 1, 'text' => 'Kabupaten Karimun'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Anambas'],
                    ['id' => 1, 'text' => 'Kabupaten Lingga'],
                    ['id' => 1, 'text' => 'Kabupaten Natuna'],
                    ['id' => 1, 'text' => 'Kota Batam'],
                    ['id' => 1, 'text' => 'Kota Tanjung Pinang'],
                ]
            ],
            [
                'text' => 'Lampung',
                'children' =>  [
                    ['id' => 1, 'text' => 'Kabupaten Lampung Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Lampung Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Lampung Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Lampung Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Lampung Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Mesuji'],
                    ['id' => 1, 'text' => 'Kabupaten Pesawaran'],
                    ['id' => 1, 'text' => 'Kabupaten Pringsewu'],
                    ['id' => 1, 'text' => 'Kabupaten Tanggamus'],
                    ['id' => 1, 'text' => 'Kabupaten Tulang Bawang'],
                    ['id' => 1, 'text' => 'Kabupaten Tulang Bawang Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Way Kanan'],
                    ['id' => 1, 'text' => 'Kabupaten Pesisir Barat'],
                    ['id' => 1, 'text' => 'Kota Bandar Lampung'],
                    ['id' => 1, 'text' => 'Kota Kotabumi'],
                    ['id' => 1, 'text' => 'Kota Liwa'],
                    ['id' => 1, 'text' => 'Kota Metro'],
                ]
            ],
            [
                'text' => 'Maluku',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Buru'],
                    ['id' => 1, 'text' => 'Kabupaten Buru Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Aru'],
                    ['id' => 1, 'text' => 'Kabupaten Maluku Barat Daya'],
                    ['id' => 1, 'text' => 'Kabupaten Maluku Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Maluku Tenggara'],
                    ['id' => 1, 'text' => 'Kabupaten Maluku Tenggara Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Seram Bagian Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Seram Bagian Timur'],
                    ['id' => 1, 'text' => 'Kota Ambon'],
                    ['id' => 1, 'text' => 'Kota Tual'],
                ]
            ],
            [
                'text' => 'Maluku Utara',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Halmahera Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Halmahera Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Halmahera Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Halmahera Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Halmahera Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Sula'],
                    ['id' => 1, 'text' => 'Kabupaten Pulau Morotai'],
                    ['id' => 1, 'text' => 'Kabupaten Pulau Taliabu'],
                    ['id' => 1, 'text' => 'Kota Ternate'],
                    ['id' => 1, 'text' => 'Kota Tidore Kepulauan'],
                ]
            ],
            [
                'text' => 'Nusa Tenggara Barat',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bima'],
                    ['id' => 1, 'text' => 'Kabupaten Dompu'],
                    ['id' => 1, 'text' => 'Kabupaten Lombok Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Lombok Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Lombok Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Lombok Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Sumbawa'],
                    ['id' => 1, 'text' => 'Kabupaten Sumbawa Barat'],
                    ['id' => 1, 'text' => 'Kota Bima'],
                    ['id' => 1, 'text' => 'Kota Mataram'],
                ]
            ],
            [
                'text' => 'Nusa Tenggara Timur',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Alor'],
                    ['id' => 1, 'text' => 'Kabupaten Belu'],
                    ['id' => 1, 'text' => 'Kabupaten Ende'],
                    ['id' => 1, 'text' => 'Kabupaten Flores Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Kupang'],
                    ['id' => 1, 'text' => 'Kabupaten Lembata'],
                    ['id' => 1, 'text' => 'Kabupaten Manggarai'],
                    ['id' => 1, 'text' => 'Kabupaten Manggarai Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Manggarai Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Ngada'],
                    ['id' => 1, 'text' => 'Kabupaten Nagekeo'],
                    ['id' => 1, 'text' => 'Kabupaten Rote Ndao'],
                    ['id' => 1, 'text' => 'Kabupaten Sabu Raijua'],
                    ['id' => 1, 'text' => 'Kabupaten Sikka'],
                    ['id' => 1, 'text' => 'Kabupaten Sumba Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Sumba Barat Daya'],
                    ['id' => 1, 'text' => 'Kabupaten Sumba Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Sumba Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Timor Tengah Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Timor Tengah Utara'],
                    ['id' => 1, 'text' => 'Kota Kupang'],
                ]
            ],
            [
                'text' => 'Papua',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Asmat'],
                    ['id' => 1, 'text' => 'Kabupaten Biak Numfor'],
                    ['id' => 1, 'text' => 'Kabupaten Boven Digoel'],
                    ['id' => 1, 'text' => 'Kabupaten Deiyai'],
                    ['id' => 1, 'text' => 'Kabupaten Dogiyai'],
                    ['id' => 1, 'text' => 'Kabupaten Intan Jaya'],
                    ['id' => 1, 'text' => 'Kabupaten Jayapura'],
                    ['id' => 1, 'text' => 'Kabupaten Jayawijaya'],
                    ['id' => 1, 'text' => 'Kabupaten Keerom'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Yapen'],
                    ['id' => 1, 'text' => 'Kabupaten Lanny Jaya'],
                    ['id' => 1, 'text' => 'Kabupaten Mamberamo Raya'],
                    ['id' => 1, 'text' => 'Kabupaten Mamberamo Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Mappi'],
                    ['id' => 1, 'text' => 'Kabupaten Merauke'],
                    ['id' => 1, 'text' => 'Kabupaten Mimika'],
                    ['id' => 1, 'text' => 'Kabupaten Nabire'],
                    ['id' => 1, 'text' => 'Kabupaten Nduga'],
                    ['id' => 1, 'text' => 'Kabupaten Paniai'],
                    ['id' => 1, 'text' => 'Kabupaten Pegunungan Bintang'],
                    ['id' => 1, 'text' => 'Kabupaten Puncak'],
                    ['id' => 1, 'text' => 'Kabupaten Puncak Jaya'],
                    ['id' => 1, 'text' => 'Kabupaten Sarmi'],
                    ['id' => 1, 'text' => 'Kabupaten Supiori'],
                    ['id' => 1, 'text' => 'Kabupaten Tolikara'],
                    ['id' => 1, 'text' => 'Kabupaten Waropen'],
                    ['id' => 1, 'text' => 'Kabupaten Yahukimo'],
                    ['id' => 1, 'text' => 'Kabupaten Yalimo'],
                    ['id' => 1, 'text' => 'Kota Jayapura'],
                ]
            ],
            [
                'text' => 'Papua Barat',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Fakfak'],
                    ['id' => 1, 'text' => 'Kabupaten Kaimana'],
                    ['id' => 1, 'text' => 'Kabupaten Manokwari'],
                    ['id' => 1, 'text' => 'Kabupaten Manokwari Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Maybrat'],
                    ['id' => 1, 'text' => 'Kabupaten Pegunungan Arfak'],
                    ['id' => 1, 'text' => 'Kabupaten Raja Ampat'],
                    ['id' => 1, 'text' => 'Kabupaten Sorong'],
                    ['id' => 1, 'text' => 'Kabupaten Sorong Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Tambrauw'],
                    ['id' => 1, 'text' => 'Kabupaten Teluk Bintuni'],
                    ['id' => 1, 'text' => 'Kabupaten Teluk Wondama'],
                    ['id' => 1, 'text' => 'Kota Sorong'],
                ]
            ],
            [
                'text' => 'Riau',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bengkalis'],
                    ['id' => 1, 'text' => 'Kabupaten Indragiri Hilir'],
                    ['id' => 1, 'text' => 'Kabupaten Indragiri Hulu'],
                    ['id' => 1, 'text' => 'Kabupaten Kampar'],
                    ['id' => 1, 'text' => 'Kabupaten Kuantan Singingi'],
                    ['id' => 1, 'text' => 'Kabupaten Pelalawan'],
                    ['id' => 1, 'text' => 'Kabupaten Rokan Hilir'],
                    ['id' => 1, 'text' => 'Kabupaten Rokan Hulu'],
                    ['id' => 1, 'text' => 'Kabupaten Siak'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Meranti'],
                    ['id' => 1, 'text' => 'Kota Dumai'],
                    ['id' => 1, 'text' => 'Kota Pekanbaru'],
                ]
            ],
            [
                'text' => 'Sulawesi Barat',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Majene'],
                    ['id' => 1, 'text' => 'Kabupaten Mamasa'],
                    ['id' => 1, 'text' => 'Kabupaten Mamuju'],
                    ['id' => 1, 'text' => 'Kabupaten Mamuju Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Polewali Mandar'],
                    ['id' => 1, 'text' => 'Kabupaten Mamuju Tengah'],
                ]
            ],
            [
                'text' => 'Sulawesi Selatan',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bantaeng'],
                    ['id' => 1, 'text' => 'Kabupaten Barru'],
                    ['id' => 1, 'text' => 'Kabupaten Bone	Watampone'],
                    ['id' => 1, 'text' => 'Kabupaten Bulukumba'],
                    ['id' => 1, 'text' => 'Kabupaten Enrekang'],
                    ['id' => 1, 'text' => 'Kabupaten Gowa'],
                    ['id' => 1, 'text' => 'Kabupaten Jeneponto'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Selayar'],
                    ['id' => 1, 'text' => 'Kabupaten Luwu'],
                    ['id' => 1, 'text' => 'Kabupaten Luwu Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Luwu Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Maros'],
                    ['id' => 1, 'text' => 'Kabupaten Pangkajene dan Kepulauan'],
                    ['id' => 1, 'text' => 'Kabupaten Pinrang'],
                    ['id' => 1, 'text' => 'Kabupaten Sidenreng Rappang'],
                    ['id' => 1, 'text' => 'Kabupaten Sinjai'],
                    ['id' => 1, 'text' => 'Kabupaten Soppeng'],
                    ['id' => 1, 'text' => 'Kabupaten Takalar'],
                    ['id' => 1, 'text' => 'Kabupaten Tana Toraja'],
                    ['id' => 1, 'text' => 'Kabupaten Toraja Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Wajo'],
                    ['id' => 1, 'text' => 'Kota Makassar'],
                    ['id' => 1, 'text' => 'Kota Palopo'],
                    ['id' => 1, 'text' => 'Kota Parepare'],
                ]
            ],
            [
                'text' => 'Sulawesi Tengah',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Banggai'],
                    ['id' => 1, 'text' => 'Kabupaten Banggai Kepulauan'],
                    ['id' => 1, 'text' => 'Kabupaten Banggai Laut'],
                    ['id' => 1, 'text' => 'Kabupaten Buol'],
                    ['id' => 1, 'text' => 'Kabupaten Donggala'],
                    ['id' => 1, 'text' => 'Kabupaten Morowali'],
                    ['id' => 1, 'text' => 'Kabupaten Parigi Moutong'],
                    ['id' => 1, 'text' => 'Kabupaten Poso'],
                    ['id' => 1, 'text' => 'Kabupaten Sigi'],
                    ['id' => 1, 'text' => 'Kabupaten Tojo Una-Una'],
                    ['id' => 1, 'text' => 'Kabupaten Tolitoli'],
                    ['id' => 1, 'text' => 'Kota Palu'],
                ]
            ],
            [
                'text' => 'Sulawesi Tenggara',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bombana'],
                    ['id' => 1, 'text' => 'Kabupaten Buton'],
                    ['id' => 1, 'text' => 'Kabupaten Buton Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Kolaka'],
                    ['id' => 1, 'text' => 'Kabupaten Kolaka Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Kolaka Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Konawe'],
                    ['id' => 1, 'text' => 'Kabupaten Konawe Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Konawe Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Konawe Kepulauan'],
                    ['id' => 1, 'text' => 'Kabupaten Muna'],
                    ['id' => 1, 'text' => 'Kabupaten Wakatobi'],
                    ['id' => 1, 'text' => 'Kota Bau-Bau'],
                    ['id' => 1, 'text' => 'Kota Kendari'],
                ]
            ],
            [
                'text' => 'Sulawesi Utara',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Bolaang Mongondow'],
                    ['id' => 1, 'text' => 'Kabupaten Bolaang Mongondow Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Bolaang Mongondow Timur'],
                    ['id' => 1, 'text' => 'Kabupaten Bolaang Mongondow Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Sangihe'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Siau Tagulandang Biaro'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Talaud'],
                    ['id' => 1, 'text' => 'Kabupaten Minahasa'],
                    ['id' => 1, 'text' => 'Kabupaten Minahasa Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Minahasa Tenggara'],
                    ['id' => 1, 'text' => 'Kabupaten Minahasa Utara'],
                    ['id' => 1, 'text' => 'Kota Bitung'],
                    ['id' => 1, 'text' => 'Kota Kotamobagu'],
                    ['id' => 1, 'text' => 'Kota Manado'],
                    ['id' => 1, 'text' => 'Kota Tomohon'],
                ]
            ],
            [
                'text' => 'Sumatera Barat',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Agam'],
                    ['id' => 1, 'text' => 'Kabupaten Dharmasraya'],
                    ['id' => 1, 'text' => 'Kabupaten Kepulauan Mentawai'],
                    ['id' => 1, 'text' => 'Kabupaten Lima Puluh Kota'],
                    ['id' => 1, 'text' => 'Kabupaten Padang Pariaman'],
                    ['id' => 1, 'text' => 'Kabupaten Pasaman'],
                    ['id' => 1, 'text' => 'Kabupaten Pasaman Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Pesisir Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Sijunjung'],
                    ['id' => 1, 'text' => 'Kabupaten Solok'],
                    ['id' => 1, 'text' => 'Kabupaten Solok Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Tanah Datar'],
                    ['id' => 1, 'text' => 'Kota Bukittinggi'],
                    ['id' => 1, 'text' => 'Kota Padang'],
                    ['id' => 1, 'text' => 'Kota Padangpanjang'],
                    ['id' => 1, 'text' => 'Kota Pariaman'],
                    ['id' => 1, 'text' => 'Kota Payakumbuh'],
                    ['id' => 1, 'text' => 'Kota Sawahlunto'],
                    ['id' => 1, 'text' => 'Kota Solok'],
                ]
            ],
            [
                'text' => 'Sumatera Selatan',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Banyuasin'],
                    ['id' => 1, 'text' => 'Kabupaten Empat Lawang'],
                    ['id' => 1, 'text' => 'Kabupaten Lahat'],
                    ['id' => 1, 'text' => 'Kabupaten Muara Enim'],
                    ['id' => 1, 'text' => 'Kabupaten Musi Banyuasin'],
                    ['id' => 1, 'text' => 'Kabupaten Musi Rawas'],
                    ['id' => 1, 'text' => 'Kabupaten Ogan Ilir'],
                    ['id' => 1, 'text' => 'Kabupaten Ogan Komering Ilir'],
                    ['id' => 1, 'text' => 'Kabupaten Ogan Komering Ulu'],
                    ['id' => 1, 'text' => 'Kabupaten Ogan Komering Ulu Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Penukal Abab Lematang Ilir'],
                    ['id' => 1, 'text' => 'Kabupaten Ogan Komering Ulu Timur'],
                    ['id' => 1, 'text' => 'Kota Lubuklinggau'],
                    ['id' => 1, 'text' => 'Kota Pagar Alam'],
                    ['id' => 1, 'text' => 'Kota Palembang'],
                    ['id' => 1, 'text' => 'Kota Prabumulih'],
                ]
            ],
            [
                'text' => 'Sumatera Utara',
                'children' => [
                    ['id' => 1, 'text' => 'Kabupaten Asahan'],
                    ['id' => 1, 'text' => 'Kabupaten Batubara'],
                    ['id' => 1, 'text' => 'Kabupaten Dairi'],
                    ['id' => 1, 'text' => 'Kabupaten Deli Serdang'],
                    ['id' => 1, 'text' => 'Kabupaten Humbang Hasundutan'],
                    ['id' => 1, 'text' => 'Kabupaten Karo	Kabanjahe'],
                    ['id' => 1, 'text' => 'Kabupaten Labuhanbatu'],
                    ['id' => 1, 'text' => 'Kabupaten Labuhanbatu Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Labuhanbatu Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Langkat'],
                    ['id' => 1, 'text' => 'Kabupaten Mandailing Natal'],
                    ['id' => 1, 'text' => 'Kabupaten Nias'],
                    ['id' => 1, 'text' => 'Kabupaten Nias Barat'],
                    ['id' => 1, 'text' => 'Kabupaten Nias Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Nias Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Padang Lawas'],
                    ['id' => 1, 'text' => 'Kabupaten Padang Lawas Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Pakpak Bharat'],
                    ['id' => 1, 'text' => 'Kabupaten Samosir'],
                    ['id' => 1, 'text' => 'Kabupaten Serdang Bedagai'],
                    ['id' => 1, 'text' => 'Kabupaten Simalungun'],
                    ['id' => 1, 'text' => 'Kabupaten Tapanuli Selatan'],
                    ['id' => 1, 'text' => 'Kabupaten Tapanuli Tengah'],
                    ['id' => 1, 'text' => 'Kabupaten Tapanuli Utara'],
                    ['id' => 1, 'text' => 'Kabupaten Toba Samosir'],
                    ['id' => 1, 'text' => 'Kota Binjai'],
                    ['id' => 1, 'text' => 'Kota Gunungsitoli'],
                    ['id' => 1, 'text' => 'Kota Medan'],
                    ['id' => 1, 'text' => 'Kota Padangsidempuan'],
                    ['id' => 1, 'text' => 'Kota Pematangsiantar'],
                    ['id' => 1, 'text' => 'Kota Sibolga'],
                    ['id' => 1, 'text' => 'Kota Tanjungbalai'],
                    ['id' => 1, 'text' => 'Kota Tebing Tinggi'],
                ]
            ]
        ];
    }
}
